version: '3.8'

services:
  backend:
    build: ./backend
    image: ghcr.io/abhas20/lms-backend:latest
    container_name: lms_backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    restart: unless-stopped

  stem-backend:
    build: ./stem/stem_backend
    image: ghcr.io/abhas20/lms-stem-backend:latest
    container_name: lms_stem_backend
    ports:
      - "5001:5001"
    env_file:
      - ./stem/stem_backend/.env
    restart: unless-stopped

  stem-frontend:
    build: ./stem/stem_frontend
    image: ghcr.io/abhas20/lms-stem-frontend:latest
    container_name: lms_stem_frontend
    ports:
      - "3000:80"
    env_file:
      - ./stem/stem_frontend/.env
    depends_on:
      - stem-backend
    restart: unless-stopped

  frontend:
    build: ./frontend
    image: ghcr.io/abhas20/lms-frontend:latest
    container_name: lms_frontend
    ports:
      - "5173:80"
    env_file:
      - ./frontend/.env
    depends_on:
      - backend
    restart: unless-stopped